### PR TITLE
Feature skeleton

### PR DESCRIPTION
**Pull request by lusekayz**
Portfolio: setup and mobile version skeleton

### CODE REVIEW

**Review by AnselemOdims — COMMENTED** [review]
# Invalid Request 🛑 

Please make sure the linters are properly set up when you start working on a project.
Check out this [link](https://github.com/microverseinc/linters-config/tree/master/html-css-js) to see how to do it.

## Optional suggestions
_Comments with the [OPTIONAL] prefix are not a must to implement however, It's strongly recommended to work on them as they can make your code better._

## Happy coding!👏👏👏

#### Please leave any questions or comments in the PR if you have any doubts or unclarity!. You can tag me with @AnselemOdims for a quicker response.

**_Note: Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

**Comment by lusekayz** [comment]
Hie

I don't understand this feedback. Please assist in pointing this out where
I went wrong.

Best Regards

**Comment by AnselemOdims** [comment]
Hi @lusekayz, 
One of the general requirements of this milestone is to make sure linters are properly setup.
It is important that you meet all requirements before your project can be approved.
See the [requirements](https://github.com/microverseinc/curriculum-html-css/blob/main/portfolio/1_setup.md) for a better understanding.

**Comment by lusekayz** [comment]
Hie @AnselemOdims

I have merged my branch repo to the main thereafter PUSHED to github.
Please check this link and advise as I am stuck.

https://github.com/lusekayz/Portfolio-setup-and-mobile-version-skeleton/tree/main

Regards

**Pull request merged**
